services:
  app:
    build: .
    image: 127.0.0.1:5000/app
    command: ["fastapi", "run", "app/main.py", "--port", "80"]
    volumes:
      - ./data:/code/data

  nginx:
    build: ./nginx
    image: 127.0.0.1:5000/nginx
    container_name: nginx
    ports:
      - '8008:80'
    depends_on:
      - app

  model:
    build: .
    image: 127.0.0.1:5000/model
    command: ["fastapi", "run", "app/model.py", "--port", "80"]
    volumes:
      - ./model:/code/model
