services:
  app:
    image: 127.0.0.1:5000/app
    command: ["fastapi", "run", "app/main.py", "--port", "80"]
    networks:
      - proxy
    volumes:
      - ../data:/code/data
      - ../model/model_features.json:/code/model/model_features.json

  nginx:
    image: nginx:1.29.0
    ports:
      - 8008:80
      - 8080:81
    depends_on:
      - app
    networks:
      - proxy
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
        mode: 0400

configs:
  nginx-config:
    file: ../nginx/nginx.conf
    name: nginx-config

networks:
  proxy:
    external: true
