services:
  app:
    image: 127.0.0.1:5000/app
    command: ["fastapi", "run", "app/main.py", "--port", "80"]
    networks:
    - proxy

  nginx:
    image: nginx
    ports:
    - '8008:80'
    depends_on:
    - app
    networks:
    - proxy
    configs:
    - source: nginx-config
      target: /etc/nginx/conf.d/default.conf
      mode: 0400

configs:
  nginx-config:
    file: ../nginx/nginx.conf
    name: nginx-config

networks:
  proxy:
    external: true
