LOG_LEVEL_ENV = "LOG_LEVEL"

MODEL_ENDPOINT_ENV = "MODEL_ENDPOINT"
MODEL_FILE_ENV = "MODEL_FILE"
MODEL_FEATURES_FILE_ENV = "MODEL_FEATURES_FILE"


ADD_DATA_LOCATION_ENV = "ADD_DATA_LOCATION"
INVOCATION_URL_ENV = "INVOCATION_URL"
FULL_ENV = "FULL"
